// Objetos JSON;
var quizDeck = [ 
    {   
        question : "Qual o nome da empresa do Minecraft?",
        imgsrc : "./images/card1.jpg",
        a : "Mojang",
        b : "Xbox Corporation", 
        c : "Java Corporation", 
        d : "Notch Corporation", 
        id1 : "q1altA",
        id2 : "q1altB",
        id3 : "q1altC",
        id4 : "q1altD",
        nameId : "q1Name",
        score : 10
    },
    {   
        question : "Quem criou o Minecraft?",
        imgsrc : "./images/card2.jpg",
        a : "Faustão",
        b : "Átila", 
        c : "Notch", 
        d : "Jorge", 
        id1 : "q2altA",
        id2 : "q2altB",
        id3 : "q2altC",
        id4 : "q2altD",
        nameId : "q2Name",
        score : 10,
    },
    {   
        question : "Quem comprou o Minecraft?",
        imgsrc : "./images/card3.jpg",
        a : "Sony",
        b : "Silvio Santos", 
        c : "Microsoft", 
        d : "Samsung", 
        id1 : "q3altA",
        id2 : "q3altB",
        id3 : "q3altC",
        id4 : "q3altD",
        nameId : "q3Name",
        score : 10,

    },
    {   
        question : "Qual foi o ano de lançamento do Minecraft?",
        imgsrc : "./images/card4.jpg",
        a : "2005",
        b : "2009", 
        c : "2006", 
        d : "2008", 
        id1 : "q4altA",
        id2 : "q4altB",
        id3 : "q4altC",
        id4 : "q4altD",
        nameId : "q4Name",
        score : 25,
    },
    {   
        question : "Qual o nome do Personagem Principal do Minecraft?",
        imgsrc : "./images/card5.jpg",
        a : "Simas",
        b : "Stivas", 
        c : "Stanho", 
        d : "Steve", 
        id1 : "q5altA",
        id2 : "q5altB",
        id3 : "q5altC",
        id4 : "q5altD",
        nameId : "q5Name",
        score : 1,
    },
    {   
        question : "Qual o mob que nasce no meio do mar?",
        imgsrc : "./images/card6.jpg",
        a : "Afogado",
        b : "Jaguatirica", 
        c : "Cachorro", 
        d : "Lagarto", 
        id1 : "q6altA",
        id2 : "q6altB",
        id3 : "q6altC",
        id4 : "q6altD",
        nameId : "q6Name",
        score : 30,
    },
    {   
        question : "Qual o monstro que tem medo de Jaguatirica??",
        imgsrc : "./images/card7.jpg",
        a : "Creeper",
        b : "Zumbi", 
        c : "Leo Stronda", 
        d : "Esqueleto", 
        id1 : "q7altA",
        id2 : "q7altB",
        id3 : "q7altC",
        id4 : "q7altD",
        nameId : "q7Name",
        score : 25,
    },
    {   
        question : "Qual o nome do dragão no final do jogo?",
        imgsrc : "./images/card8.jpg",
        a : "Regina Casé",
        b : "Ender Dragon", 
        c : "Bone Dragon", 
        d : "Final Dragon", 
        id1 : "q8altA",
        id2 : "q8altB",
        id3 : "q8altC",
        id4 : "q8altD",
        nameId : "q8Name",
        score : 10,
    },
    {   
        question : "Qual o antigo nome do jogo?",
        imgsrc : "./images/card9.jpg",
        a : "Building Game",
        b : "Cave World", 
        c : "Cave Game", 
        d : "Building World", 
        id1 : "q9altA",
        id2 : "q9altB",
        id3 : "q9altC",
        id4 : "q9altD",
        nameId : "q9Name",
        score : 35,
    },
    {   
        question : "Quais são as duas dimensões do jogo?",
        imgsrc : "./images/card10.jpg",
        a : "Nether e Aether",
        b : "The End e Aether", 
        c : "Nether e The End", 
        d : "Nether e Cave", 
        id1 : "q10altA",
        id2 : "q10altB",
        id3 : "q10altC",
        id4 : "q10altD",
        nameId : "q10Name",
        score : 10,
    },
]